ci: updates to ci and clean up of unused profiles (DNA-16592: DNA-17262)
UiPath/ProcessMining-devkit-connector pull request #115
Opened 2023-07-26 12:08 UTC by cverhoef

Can be merge to main as it is unrelated to framework updates:
- New ci pipeline versions
- SQL fluff support new version
- Cleanup unused profiles

2023-07-26 12:49 UTC, JasperSelmanUiPath requested changes

2023-07-26 12:49 UTC, JasperSelmanUiPath commented on .pipelines/azure-pipelines-transformations.yml
> +    - '*'
We explicitly had set this to only run on a trigger. This means in practice that for each push we check the transformations for partners. We did this so we did not force partners to work with PRs (at least until they want to merge). 

Personally I am fine with changing this and require from our partners to work with PRs for their work, but if we do not want this we should not change this part.

2023-07-26 12:49 UTC, JasperSelmanUiPath commented on README.md
I see we missed in previous updates to update this README. There is currently only 1 `dbt_project.yml` left, but in the README we refer on several places to two different projects.

2023-07-26 12:50 UTC, JasperSelmanUiPath commented
- The SQL contains linting issues.
- We should also update the dbt_project number or set it to the same placeholder we have in our repository.

2023-07-27 11:05 UTC, cverhoef commented on .pipelines/azure-pipelines-transformations.yml
> +    - '*'
Will put it back to the original state.

2023-07-27 11:29 UTC, JasperSelmanUiPath approved these changes

2023-07-27 11:31 UTC, merged